import {
  collectServices,
  clientFileName,
  serverFileName,
  typesFileName,
  toSnakeCase,
  type ServiceInfo,
} from "@speconn-rpc/typespec-emitter-speconn-core";
import type { EmitContext, Model } from "@typespec/compiler";
import { writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";

function rustType(m: Model | null): string {
  if (!m || !m.name) return "()";
  return m.name;
}

function rustCodec(m: Model | null): string {
  if (!m || !m.name) return "UnitCodec";
  return m.name + "Codec";
}

function collectTypeImports(svc: ServiceInfo): string[] {
  const s = new Set<string>();
  for (const r of svc.rpcs) {
    if (r.inputType && r.inputType.name) {
      s.add(rustType(r.inputType));
      s.add(rustCodec(r.inputType));
    }
    if (r.outputType && r.outputType.name) {
      s.add(rustType(r.outputType));
      s.add(rustCodec(r.outputType));
    }
  }
  return [...s].sort();
}

function regMethod(streamType: string): string {
  if (streamType === "unary") return "register_unary";
  if (streamType === "server") return "register_server_stream";
  if (streamType === "client") return "register_client_stream";
  return "register_bidi";
}

function genClient(svc: ServiceInfo): string {
  const L: string[] = [];
  L.push("// Generated by typespec-emitter-speconn-rust. DO NOT EDIT.");
  L.push("");
  L.push("use std::sync::Arc;");
  L.push("use speconn_rpc::{SpeconnCaller, SpeconnTransport, CallOptions, SpeconnError, get_default_transport};");

  const tMod = typesFileName(svc);
  const imps = collectTypeImports(svc);
  if (imps.length > 0) {
    L.push(`use crate::${tMod}::{${imps.join(", ")}};`);
  }
  L.push("");

  L.push(`pub struct ${svc.serviceName}Client {`);
  L.push("    transport: Arc<dyn SpeconnTransport + Send + Sync>,");
  L.push("}");
  L.push("");
  L.push(`impl ${svc.serviceName}Client {`);
  L.push("    pub fn new(t: Arc<dyn SpeconnTransport + Send + Sync>) -> Self {");
  L.push("        Self { transport: t }");
  L.push("    }");
  L.push("");
  L.push("    pub fn new_with_default() -> Self {");
  L.push("        Self { transport: get_default_transport() }");
  L.push("    }");
  L.push("");
  L.push("    pub fn set_transport(&mut self, t: Arc<dyn SpeconnTransport + Send + Sync>) {");
  L.push("        self.transport = t;");
  L.push("    }");
  L.push("");

  for (const rpc of svc.rpcs) {
    const rq = rustType(rpc.inputType);
    const rs = rustType(rpc.outputType);
    const rqC = rustCodec(rpc.inputType);
    const rsC = rustCodec(rpc.outputType);
    const fn = toSnakeCase(rpc.name);

    if (rpc.streamType === "client" || rpc.streamType === "bidi") {
      const ret = rpc.streamType === "bidi" ? `Vec<${rs}>` : rs;
      L.push(`    pub async fn ${fn}(&self, reqs: impl IntoIterator<Item = ${rq}>, options: CallOptions) -> Result<${ret}, SpeconnError> {`);
    } else {
      const ret = rpc.streamType === "server" ? `Vec<${rs}>` : rs;
      L.push(`    pub async fn ${fn}(&self, req: ${rq}, options: CallOptions) -> Result<${ret}, SpeconnError> {`);
    }

    L.push("        let caller = SpeconnCaller::new(");
    L.push(`            "${rpc.path}",`);
    L.push("            self.transport.clone(),");
    L.push(`            ${rqC},`);
    L.push(`            ${rsC},`);
    L.push("        );");

    if (rpc.streamType === "unary") {
      L.push("        caller.call(&req, options).await");
    } else if (rpc.streamType === "server") {
      L.push("        caller.server_stream(&req, options).await");
    } else if (rpc.streamType === "client") {
      L.push("        caller.client_stream(options, reqs).await");
    } else {
      L.push("        caller.bidi(options, reqs).await");
    }

    L.push("    }");
    L.push("");
  }

  L.push("}");
  L.push("");

  return L.join("\n");
}

function genServer(svc: ServiceInfo): string {
  const L: string[] = [];
  L.push("// Generated by typespec-emitter-speconn-rust. DO NOT EDIT.");
  L.push("");
  L.push("use std::sync::Arc;");
  L.push("use speconn_rpc::{SpeconnRouter, SpeconnContext, SpeconnError};");

  const tMod = typesFileName(svc);
  const imps = collectTypeImports(svc);
  if (imps.length > 0) {
    L.push(`use crate::${tMod}::{${imps.join(", ")}};`);
  }
  L.push("");

  const traitName = `${svc.serviceName}Service`;
  const regFn = `register_${toSnakeCase(svc.serviceName)}`;

  L.push(`pub trait ${traitName}: Send + Sync {`);
  for (const rpc of svc.rpcs) {
    const rq = rustType(rpc.inputType);
    const rs = rustType(rpc.outputType);
    const fn = toSnakeCase(rpc.name);
    if (rpc.streamType === "unary") {
      L.push(`    fn ${fn}(&self, ctx: &mut SpeconnContext, req: ${rq}) -> Result<${rs}, SpeconnError>;`);
    } else if (rpc.streamType === "server") {
      L.push(`    fn ${fn}(&self, ctx: &mut SpeconnContext, req: ${rq}) -> Vec<${rs}>;`);
    } else if (rpc.streamType === "client") {
      L.push(`    fn ${fn}(&self, ctx: &mut SpeconnContext, reqs: Vec<${rq}>) -> Result<${rs}, SpeconnError>;`);
    } else {
      L.push(`    fn ${fn}(&self, ctx: &mut SpeconnContext, reqs: Vec<${rq}>) -> Vec<${rs}>;`);
    }
  }
  L.push("}");
  L.push("");

  L.push(`pub fn ${regFn}(router: &mut SpeconnRouter, impl_: Box<dyn ${traitName}>) {`);
  L.push("    let imp = Arc::from(impl_);");
  L.push("");

  for (const rpc of svc.rpcs) {
    const rqC = rustCodec(rpc.inputType);
    const rsC = rustCodec(rpc.outputType);
    const fn = toSnakeCase(rpc.name);
    const isStream = rpc.streamType === "client" || rpc.streamType === "bidi";
    const arg = isStream ? "reqs" : "req";

    L.push("    {");
    L.push("        let imp = Arc::clone(&imp);");
    L.push(`        router.${regMethod(rpc.streamType)}(`);
    L.push(`            "${rpc.path}",`);
    L.push(`            ${rqC},`);
    L.push(`            ${rsC},`);
    L.push(`            move |ctx, ${arg}| imp.${fn}(ctx, ${arg}),`);
    L.push("        );");
    L.push("    }");
    L.push("");
  }

  L.push("}");
  L.push("");
  return L.join("\n");
}

export async function $onEmit(context: EmitContext): Promise<void> {
  const program = context.program;
  const services = collectServices(program);
  if (services.length === 0) return;

  const outDir: string = context.emitterOutputDir;
  const opts = (context as any).options ?? {};
  const emitClient = !opts["server-only"];
  const emitServer = !opts["client-only"];
  mkdirSync(outDir, { recursive: true });

  for (const svc of services) {
    if (emitClient) writeFileSync(join(outDir, `${clientFileName(svc)}.rs`), genClient(svc), "utf-8");
    if (emitServer) writeFileSync(join(outDir, `${serverFileName(svc)}.rs`), genServer(svc), "utf-8");
  }
}
